language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  - DJANGO_VERSION=2.1.2

addons:
  apt_packages:
    - swig
  ssh_known_hosts:
    - 193.40.33.98:22

before_install:
  - export DJANGO_SETTINGS_MODULE=oisbotServer.settings
  - export PYTHONPATH=$HOME/builds/diffusa/djangoapp
  - export PIP_USE_MIRRORS=true
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in tvp2017-dumas.pem.enc -out tvp2017-dumas.pem -d
install:
  - pip install -q Django==$2.1.2
  - pip install djangorestframework
  - pip install requests
  - pip install estnltk==1.6.0b0 --quiet
script: python -m unittest tests/testsWithoutSIS2.py
after_success:
  - eval "$(ssh-agent -s)" # Start ssh-agent cache
  - chmod 600 tvp2017-dumas.pem # Allow read access to the private key
  - ssh-add tvp2017-dumas.pem # Add the private key to SSH

  - git remote add deploy https://github.com/Terminaator/chatbot.git@193.40.33.98:22:/var/www/chatbot2/chatbot/.git
  - git push deploy master