language: python
matrix:
  include:
    - python: 3.6.7
      dist: xenial
      sudo: true
env:
  - DJANGO_VERSION=2.1.4

addons:
  apt_packages:
    - swig
  ssh_known_hosts:
    - 193.40.33.98:22

before_install:
  - export DJANGO_SETTINGS_MODULE=oisbotServer.settings
  - export PYTHONPATH=$HOME/builds/diffusa/djangoapp
  - export PIP_USE_MIRRORS=true
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in tvp2017-dumas.pem.enc -out tvp2017-dumas.pem -d
install:
  - pip install -q Django==$2.1.4
  - pip install djangorestframework
  - pip install requests
  - pip install beautifulsoup4
  - pip install estnltk==1.6.0b0 --quiet

script:
  - python -m unittest tests/TestsWithoutSIS2.py
  - python -m unittest tests/TestsUsingMock.py
after_success:
  - bash deploy.sh